global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: shortener
    metrics_path: /metrics
    static_configs:
      - targets:
          - shortener-dev:80
          - shortener-prod:80

  - job_name: kgs
    metrics_path: /metrics
    static_configs:
      - targets:
          - kgs-dev:80
          - kgs-prod:80
